### ISSUE TITLE
--macro include file 

### ISSUE THREAD

**Issue by markknol** [back2dos/closure#8]
Hi Juraj ,

Thanks for this library, it's neat!
I want to use `Compiler.includeFile` in my hxml files to add JavaScript libraries into my build. But I basically want to add them _after_ the closure compiler has run (I don't want to minify twice or use the debug builds of that lib (some have errors/warnings). It doesn't seem to matter how I order my `-lib closure` and this include.

`--macro haxe.macro.Compiler.includeFile("source/library/qwerqwer.min.js")`

Is that possible?

**Comment by back2dos** [comment]
In short, I don't think you can do it. This lib runs closure *after* generation (because closure can only process a JS file that exists), while `includeFile` basically runs *during* generation. One might be able to pull some really fancy stunts with custom generators, but I don't think you want to go there.

I guess the easiest thing would be to do something like `--next -cmd "cat vendor.js output.js > combined.js"`. Or you know `--next --run PostBuild` and go completely wild in `PostBuild.hx` ;)

Another thought that I'd like you to consider: if closure is invoked on the combined source, it is safe to use advanced mode without any externs whatsoever. 

Concatenating and then minifying is generally better than the other way round, because minifcation tends to be much smarter than concatenation. Developing that thought I'd say it shouldn't be too hard to add source map support to this lib so then you can just minify all *and* have readable code for debugging \o/

**Comment by markknol** [comment]
Thanks, kind of what I thought. I use pixi for example which gives quite some warnings+errors in closure compiler.  I just saw there are closure externs for that (not sure how up to date) but I have no idea how to plug those.

Also, warnings seem to stop the closure compiler, not sure how you deal with that.

I like the idea of making advanced mode work, I never got that to work before because it didn't compile or didn't run.. I started [this thing](https://github.com/markknol/hxobfuscator) to see if I could do some extra minification myself, but advanced mode would be ideal of course.

**Comment by back2dos** [comment]
> Also, warnings seem to stop the closure compiler, not sure how you deal with that.

Suppressing warnings shouldn't be too hard, but I don't think that it should stop compilation anyway. Which pixi version and distribution are you using?

**Comment by markknol** [comment]
Im using latest, 4.4.3

**Comment by markknol** [comment]
Fixed with latest commits. Seems to need specific `language_in` version.
